### ISSUE TITLE
I get following error and I  don't know what does this mean.

### ISSUE THREAD

**Issue by ejaz-ahmed** [mike-plummer/Grails_WebSockets#1]
grails run-app| Error Failed to compile idea-list-injected-traits.groovy: startup failed:
idea-list-injected-traits.groovy: 2: unable to resolve class org.grails.compiler.injection.TraitInjectionSupport
 @ line 2, column 1.
   import org.grails.compiler.injection.TraitInjectionSupport
   ^

1 error
 (Use --stacktrace to see the full trace)
| Error Error occurred running Grails CLI: null (Use --stacktrace to see the full trace)

**Comment by mike-plummer** [comment]
I need a bit more information:
1. What version of Grails are you using? `grails -version`
2. Are you running from the command line or within an IDE like IntelliJ IDEA? If an IDE, what version?

**Comment by ejaz-ahmed** [comment]
i  am running from command line with grails 3.0.1

**Comment by mike-plummer** [comment]
I think you need to double-check your setup - according to the [documentation](http://grails.github.io/grails-doc/3.0.3/api/org/grails/compiler/injection/TraitInjectionSupport.html) the "org.grails.compiler.injection.TraitInjectionSupport" class referenced by your error was introduced in Grails 3.0.3, so you're obviously not running 3.0.1.

You could try deleting your ~/.gradle directory and rebooting to see if there are old JARs from your cache polluting the classpath.

**Comment by ejaz-ahmed** [comment]
I'm indeed running grails 3.0.1. Can't afford deleting .gradle right now. I'll investigate it further and let you know. By the way, does your application works versions later than 3.0.1?

**Comment by ejaz-ahmed** [comment]
Done. The problem was in .grails/repository directory which contained idea-list-injected-traits.groovy file. It seemed to auto-generated by intellij for grails 3.1.0.M2. After removing this directory, the issue got resolved.
