### ISSUE TITLE
Canno run web app

### ISSUE THREAD

**Issue by ghost** [mike-plummer/Grails_WebSockets#2]
Hi, i can't run the webapp. I've the following error: "Error Error initializing classpath: Unsupported method: GrailsClasspath.getError()", and the following configuration: Grails Version: 3.0.9, Groovy Version: 2.4.5, JVM Version: 1.8.0_60, Gradle 2.8. What's wrong with it, for it to not work? Thx

**Comment by mike-plummer** [comment]
I ran into this same issue a few days ago which caused me to add the "Important Grails Note" section to the README. Basically, even though you have updated your Gradle installation there are still some incompatible Gradle JARs on the Gradle daemon's classpath which cause issues with Grails. I ended up having to kill all Gradle-related processes on my system then delete the ~/.gradle directory. After that things worked just fine. You should be able to do the following:
1. `gradle --stop`
2. `ps -ef | grep gradle` , execute `kill {PID}` for each process if there are any (Make sure you don't kill anything you shouldn't!)
3. `rm -rf ~/.gradle` - this will delete your Gradle cache
4. Reboot (just to be safe)
5. Re-run Grails and it should work

**Comment by ghost** [comment]
Hi , i've just read your README.md but the problem persist. It's strange! A blank app create with grails 3.0.1 doesn't run and give this error 'unable to resolve class org.grails.compiler.injection.TraitInjectionSupport'. I solved the problem by creating a blank app with grails 3.0.9 and by importing your code in. All work correctly now and seems to work with gradle 2.3.

**Comment by mike-plummer** [comment]
You may have run into the same issue as [this](https://github.com/mike-plummer/Grails_WebSockets/issues/1). Regardless, glad it's working for you.
