### ISSUE TITLE
Same thing, using Socket.IO?

### ISSUE THREAD

**Issue by mautematico** [mike-plummer/Grails_WebSockets#3]
Hola, Mike!

I am wondering how to use socket.io in a similar form you're using spring-websocket. Could you please point me on some resources direction? :)

Thank you!

**Comment by mike-plummer** [comment]
You want to use Socket.io in a Grails application? Socket.io is for managing sockets in Javascript whereas this project handles management in the JVM via Spring & Grails. You could theoretically launch socket.io side-by-side with Grails but you would need to work out a way to move data between the two. If you're just looking for advice on how to get started with Socket.io I would recommend looking at their [docs](http://socket.io/docs/) and following the Node or Express tutorials.

**Comment by mautematico** [comment]
My fault. I meant https://github.com/mrniko/netty-socketio, which is a Java port of socket.io :)

I've got already a "manual" netty-socketio server on my grails aplication, which I've succesfully connected to my HTML5+JavaScrpit (socket.io) Front-end, but I was wondering if there is a "right" way to do it, specially involving spring security.
